package com.lucas.sportsdemo.api

data class GameCardUiModel(
    val team1: String,
    val team2: String,
    val team1Id: String?,
    val team2Id: String?,
    val team1Record: String?,
    val team2Record: String?,
    val team1Rank: Int?,
    val team2Rank: Int?,
    val team1Abr: String?,
    val team2Abr: String?,
    val startTime: String?,
    val spread: Double?,
    val team1Logo: String?,
    val team2Logo: String?,
    val team1Color: String?,
    val team2Color: String?,
    val broadcast: String? = null,
    val status: GameStatus,
    val homeScore:  String?,
    val awayScore: String?,
    val homeWinner: Boolean?,
    val awayWinner: Boolean?,
    val displayClock: String?,
    val period: Int?,
    val shortDetail: String?,
    val possession: String?,
    val shortDownDistanceText: String?,
    val possessionText: String?
)